displayName=StrongBuffs
author=Jesse de Zwart
description=A weakauras (WoW) like plugin for RuneLite. Only support for explicitly approved features.
tags=
plugins=nl.jessedezwart.strongbuffs.StrongBuffsPlugin
